[supervisord]
nodaemon=false
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:cedarstar]
command=python main.py
directory=/opt/cedarstar
autostart=true
autorestart=true
startsecs=10
startretries=3
stderr_logfile=/var/log/supervisor/cedarstar.err.log
stdout_logfile=/var/log/supervisor/cedarstar.out.log
environment=PATH="/opt/cedarstar/venv/bin:%(ENV_PATH)s"
user=root
